[package]
name = "cod-node-derive"
version = "0.1.0"
authors = ["Roope Salmi <rpsalmi@gmail.com>", "George Atkinson <geomyles@yahoo.co.uk>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
proc-macro2 = "1.0"
quote = "1.0"